version: "{branch} #{build}"

branches:
  only:
    - master

image: Visual Studio 2017

platform: x64

configuration: Release

shallow_clone: true

matrix:
  fast_finish: false

environment:
  matrix:
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
  - ps: 'Write-Host "Building GEOS branch: $env:APPVEYOR_REPO_BRANCH" -ForegroundColor Magenta'

before_build:
  - ps: 'Write-Host "Running $env:BUILDER with $env:GENERATOR" -ForegroundColor Magenta'
  - cd build
  - if "%BUILDER%"=="CMake" cmake.exe .. -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DTARGET_CPU=$PLATFORM

build_script:
  - ps: 'Write-Host "Running $env:BUILDER:" -ForegroundColor Magenta'
  - if "%BUILDER%"=="CMake" cmake --build . --config %CONFIGURATION%

test_script:
  - ps: 'Write-Host "Running tests:" -ForegroundColor Magenta'
  - if "%BUILDER%"=="CMake" ctest -V --output-on-failure -C %CONFIGURATION%